### ISSUE TITLE
preact serve deprecated in preact-cli v3.0.0-rc.6

### ISSUE THREAD

**Issue by jennydaman** [preactjs-templates/simple#12]
https://github.com/preactjs-templates/simple/blob/d8065653566719fda85115ff43c3126da4d764ce/template/package.json#L9

**Comment by prateekbh** [comment]
Sorry, can you explain the issue here?

**Comment by jennydaman** [comment]
https://github.com/preactjs-templates/simple/blob/d8065653566719fda85115ff43c3126da4d764ce/template/package.json#L21

Code uses preact-cli version 3.0.0-rc.6, in which the command `preact serve` has been deprecated (i.e. is not an option anymore).

https://github.com/preactjs/preact-cli/releases/tag/v3.0.0-next.1

```
$ preact --help

  Usage
    $ preact <command> [options]

  Available Commands
    build     Create a production build
    create    Create a new application
    list      List official templates
    watch     Start a live-reload server for development
    info      Print out debugging information about the local environment

  For more info, run any command with the `--help` flag
    $ preact build --help
    $ preact create --help

  Options
    -v, --version    Displays current version
    -h, --help       Displays this message
```

**Comment by lukeed** [comment]
Yes, the issue is that this template has been updated to use the `rc` but `preact serve` is missing. Needs to be updated like https://github.com/preactjs-templates/typescript/pull/13 and https://github.com/preactjs-templates/default/pull/39
