### ISSUE TITLE
Invalid source tree organisation after init

### ISSUE THREAD

**Issue by zgoda** [preactjs-templates/simple#16]
When initialised with `npx preact-cli create simple myproject` the artifacts are organised in a way that results in 404 on static assets and `manifest.json`. To solve this one has to move `assets` directory and `manifest.json` into `src`.

**Comment by rschristian** [comment]
Cheers, thanks for the heads up. Looks like that was never updated along side CLI changes. I'll whip up a quick PR here for that.
