### ISSUE TITLE
Cannot use global variable named `h`

### ISSUE THREAD

**Issue by goodrone** [preactjs-templates/simple#6]
# Preparing the environment

I use `preact-cli` with the `simple` template:
```
preact create simple preact-bug-h
cd preact-bug-h
preact build
```

I verified that `Hello, World!` is displayed in the browser — as expected.

# Problem 1: `TypeError: h is not a function`

Edit `index.js` and paste the following line before `export default class App ...`:
```javascript
const h = 0;
```

Run `preact build`, get the following result:
```
TypeError: h is not a function
method: JkW7
at: /.../preact-bug-h/index.js:9:4
```

This error is quite explicit, but still it's not super obvious why `h` cannot be used here.

# Problem 2: empty page is rendered silently

Edit `index.js`, and now define `h` to be a function, for example:
```javascript
const h = () => {};
```

Run `preact build`, is finishes successfully.  Open the result page in browser — now it appears to be empty.

# Discussion

I'm sorry if this is a silly issue and thank you for looking into it.  I also hope it's an appropriate place to raise the issue.

The default `index.js` only imports `Component`:
```javascript
import { Component } from 'preact';
```

As I understand, `h` is injected when JSX is rendered by babel.  This happens behind the scene, and we probably want developers to not worry about the mechanics of this process.  However, I'm afraid that the chosen name might be a bit too common, especially in quick prototypes.  Developers new to the ecosystem might get disoriented when their project suddenly stops working.

* Maybe the `template/index.js` can be updated to also import `h`?  The ticking clock demo on the [getting started](https://preactjs.com/guide/getting-started) page does that, even though it's not being explicitly used.  I personally don't think it's the best solution, but at least it gives a hint.

* Maybe preact-cli can be reconfigured by default to use a different name, not `h`?

* Maybe preact-cli documentation can be improved to mention the use of `h`?

**Comment by lukeed** [comment]
This is because `h` is the Preact equivalent of `React.createElement`. The `h` reference is auto-injected into all pages/components so that your JSX can be transpiled. This is done with/by [`babel-plugin-transform-react-jsx`](https://www.npmjs.com/package/babel-plugin-transform-react-jsx).

Basically, imagine that every JSX template you have (w/ Preact CLI) has this at the top:

```js
import { h } from 'preact';
```

**Comment by ForsakenHarmony** [comment]
If this is still a concern, feel free to open an issue on `preact-cli` directly
